# -*- coding: utf-8 -*-
"""sales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KYc2tqyPeCodlsKVc_MYgaFwULTlSjR
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor


# Page Configuration

st.set_page_config(
    page_title="Airbnb NYC Analytics",
    layout="wide"
)

st.title("🏙 Airbnb NYC Sales Data Analysis & Price Prediction")
st.markdown("Interactive dashboard to analyze pricing trends and predict Airbnb listing prices.")

# Load Data


@st.cache_data
def load_data():
    df = pd.read_csv("AB_NYC_2019.csv")
    df = df.drop(columns=['id', 'name', 'host_name', 'last_review'])
    df['reviews_per_month'].fillna(0, inplace=True)
    df = df[df['price'] > 0]
    return df

df = load_data()


# Sidebar Filters

st.sidebar.header("🔍 Filter Listings")

room_type = st.sidebar.multiselect(
    "Room Type",
    df['room_type'].unique(),
    default=df['room_type'].unique()
)

neighbourhood = st.sidebar.multiselect(
    "Neighbourhood Group",
    df['neighbourhood_group'].unique(),
    default=df['neighbourhood_group'].unique()
)

filtered_df = df[
    (df['room_type'].isin(room_type)) &
    (df['neighbourhood_group'].isin(neighbourhood))
]

# KPI Metrics

col1, col2, col3 = st.columns(3)

col1.metric("💰 Average Price", f"${filtered_df['price'].mean():.2f}")
col2.metric("🏠 Total Listings", filtered_df.shape[0])
col3.metric("📅 Avg Availability", f"{filtered_df['availability_365'].mean():.1f}")


# Charts

st.subheader("📊 Pricing Insights")

col4, col5 = st.columns(2)

# Room Type vs Price
with col4:
    st.markdown("### Room Type vs Average Price")
    fig1, ax1 = plt.subplots()
    sns.barplot(x='room_type', y='price', data=filtered_df, ax=ax1)
    st.pyplot(fig1)

# Neighbourhood vs Price
with col5:
    st.markdown("### Neighbourhood Group vs Average Price")
    fig2, ax2 = plt.subplots()
    sns.barplot(x='neighbourhood_group', y='price', data=filtered_df, ax=ax2)
    st.pyplot(fig2)


# Scatter Plot

st.subheader("📈 Reviews vs Price Relationship")
fig3, ax3 = plt.subplots()
sns.scatterplot(
    x='number_of_reviews',
    y='price',
    data=filtered_df,
    alpha=0.5,
    ax=ax3
)
st.pyplot(fig3)

# Machine Learning Model

st.subheader("🤖 Price Prediction Model")

X = df[['neighbourhood_group', 'room_type',
        'minimum_nights', 'number_of_reviews',
        'reviews_per_month', 'availability_365']]

y = df['price']

categorical_features = ['neighbourhood_group', 'room_type']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough'
)

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(n_estimators=100, random_state=42))
])

model.fit(X, y)

# User Input for Prediction

st.markdown("### 🔮 Predict Listing Price")

col6, col7, col8 = st.columns(3)

with col6:
    nb = st.selectbox("Neighbourhood Group", df['neighbourhood_group'].unique())

with col7:
    rt = st.selectbox("Room Type", df['room_type'].unique())

with col8:
    min_nights = st.number_input("Minimum Nights", min_value=1, value=1)

reviews = st.number_input("Number of Reviews", min_value=0, value=10)
availability = st.slider("Availability (Days)", 0, 365, 180)

input_data = pd.DataFrame({
    'neighbourhood_group': [nb],
    'room_type': [rt],
    'minimum_nights': [min_nights],
    'number_of_reviews': [reviews],
    'reviews_per_month': [reviews / 12],
    'availability_365': [availability]
})

predicted_price = model.predict(input_data)[0]

st.success(f"💵 Estimated Price per Night: ${predicted_price:.2f}")

